### ISSUE TITLE
Allow to set `uuid` when adding a new `NetworkManager` connection

### ISSUE THREAD

**Issue by souliane** [martinpitt/python-dbusmock#196]
Thanks a lot for this useful project!

To allow to pass a `UUID` to `AddWiFiConnection` would be very handy.

`NetworkManager` offers some methods that use this `UUID` as identifier for the connection, so this would allow to easier test manipulation of the connections that are created with `dbusmock`.

Currently, I have found no better solution than to define an async fixture in order to retrieve the connection UUID.

**Comment by martinpitt** [comment]
This is unfortunately a bit tricky. AddWiFiConnection() is a D-Bus method, so adding arguments to it breaks the API, and optional parameters are a bit weird (usually an `a{sv}` options parameter). This function has been around since 2020, and I don't want to upset existing projects. Retrieving the UUID after the call shouldn't be hard, but if it's really painful I could add a `AddWiFiConnectionWithUUID()`

**Comment by souliane** [comment]
Hi, thanks for the answer.
I use fastapi and this is the only thing that requires me to use an async fixture. Because of it, I have to use an async client instead of the builtin fastapi test client. This can have some side effects and I struggled a bit, but in the end it's not a big deal :-)

I am closing this, feel free to reopen if you feel like adding `AddWiFiConnectionWithUUID`.
